version: '3'

services:
  mysql:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mydb
    ports:
      - "3308:3306"

  backend:
    build: ./backend-flask
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_DB: mydb
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  frontend:
    build: ./frontend-html
    environment:
      BACKEND_URL: http://backend:5000
    ports:
      - "5001:5001"
    depends_on:
      - backend
