apiVersion: v1 
kind: ConfigMap
metadata:
  name: myapp
  namespace: final-project
data:
  DB_HOST: "mysql"
  DB_PORT: "3306"
  BACKEND_PORT: "5000"
  FRONTEND_PORT: "5001"
  PROMETHEUS_PORT: "9091"
  GRAFANA_PORT: "3000"

