apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: final-project
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=   # rootpass
  MYSQL_DATABASE: bXlkYg==           # mydb
  MYSQL_USER: bXl1c2Vy               # myuser
  MYSQL_PASSWORD: bXlwYXNz           # mypass
