apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: final-project-app
  namespace: argocd   
spec:
  project: default
  source:
    repoURL: 'https://github.com/mazen2025/final-project.git'
    targetRevision: main
    path: K8s
  destination:
    server: https://kubernetes.default.svc
    namespace: final-project
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  
  
      